### ISSUE TITLE
Disabled property not worked as expected 

### ISSUE THREAD

**Issue by jmsunseri** [testing-library/svelte-testing-library#121]
I have a button component like this

```
<script lang="ts">
  export let disabled: boolean = false;
</script>

<button  {disabled} on:click>
 <slot />
</button>
```

I'm trying to test it like this

```
it('does disabled work', async () => {
  const { getByRole, component } = render(Button, {
    disabled: true,
  });
  const button = getByRole('button');
  expect(button.hasAttribute('disabled')).toBeTruthy();    <-- passes

  const mock = jest.fn();
  component.$on('click', mock);

  fireEvent.click(button);
  expect(mock).not.toHaveBeenCalled();   <-- fails
});
```

Shouldn't fireEvent.click(button) try to replicate what would happen if a user tried to click the button?

**Comment by benbender** [comment]
bump? I've stumbled about the same issue today...

**Comment by yanick** [comment]
@testing-library/svelte pretty much only import 'fireEvent' from @testing-library/dom without any change.

The 'click on disabled' issue is reported on their repo here: https://github.com/testing-library/dom-testing-library/issues/92, which itself tracks the root source to jsdom (https://github.com/jsdom/jsdom/issues/2665)

As this is an upstream problem and there is not much we can do about it, I'll close the issue here.
