### ISSUE TITLE
Strange behaviour when testing component with script context="module"

### ISSUE THREAD

**Issue by KlashReik** [testing-library/svelte-testing-library#335]
Hi! I've created TreeView  which looks similar to https://svelte.dev/repl/a3f724e24df54b9695402576ffd68fe3?version=4.2.12

But I have trouble testing it. 
The first test case works as expected. I use `await fireEvent.click(rootItem);` to fire click event. The list gets expanded and the test sees new nodes. But the second fails with this error.
<img width="646" alt="image" src="https://github.com/testing-library/svelte-testing-library/assets/107769156/d1174e85-9521-451d-87ed-3c8f3e34c20a">
<img width="324" alt="image" src="https://github.com/testing-library/svelte-testing-library/assets/107769156/e80f46ef-1017-459f-82a7-e14bc9dda1a5">

I've pasted two identical test cases and the first passed, while the second failed. To fix it I have to write `await fireEvent.click(rootItem);` two times. And every other click inside the test should be done twice to work correctly. 
<img width="366" alt="image" src="https://github.com/testing-library/svelte-testing-library/assets/107769156/92f249fd-b42b-497d-9f0a-9f75e29ec02d">
<img width="641" alt="image" src="https://github.com/testing-library/svelte-testing-library/assets/107769156/3fb8bd57-5ae8-43be-9267-d6f13c875a6c">
<img width="340" alt="image" src="https://github.com/testing-library/svelte-testing-library/assets/107769156/13aa1295-d0c3-4833-8bb4-6f0ff9cfc2c6">

How can this be fixed?

**Comment by mcous** [comment]
@KlashReik unfortunately, that is not enough information to diagnose your issue. If you were able to create a **minimal** reproduction in a repo or gist, someone might be able to help further.

Without much to go on here, I recommend you investigate:

- Use [`testing-library/user-event`](https://testing-library.com/docs/user-event/intro/) rather than `fireEvent`
- Use async [`findByText`](https://testing-library.com/docs/dom-testing-library/api-async/#findby-queries) rather than getByText
    - Note: I usually find that needing to rely on `findByText` is an indication of some sort of bug and/or structural deficiency in your tests or code

**Comment by KlashReik** [comment]
Hi @mcous,

I'm sorry, have been busy lately, thus sharing an example repo only now.
https://github.com/KlashReik/svelte-testing-library

**Comment by mcous** [comment]
@KlashReik the issue appears to be with your component, not `svelte-testing-library`. `<script context="module">` is module-leve, which means means any objects you place there - like `_expansionState` are persisted across tests. The reason your second test requires two-clicks is because of cross-test state pollution.

You would have this same issue if you were writing vanilla JavaScript:

```js
// my-module.js
const state = {}

export const setValue = (name, value) => {
  state[name] = value
  return state
}

// my-module.spec.js
import { test, expect } from 'vitest'

import { state, setValue } from './my-module.js'

test('set string value', () => {
  const result = setValue('hello', 'world')
  expect(result).toEqual({ hello: 'world' })
})

test('set number value', () => {
  const result = setValue('blue', 42)
  expect(result).toEqual({ blue: 42 })
})
// fail, `{ hello: 'world', blue: 42 }` does not equal { `blue: 42 }`
```

You can see this by removing _all_ clicks after the first test (or using `screen.debug()` in your tests); the second and third tests will pass without any clicks, because `_expansionState` is a singleton.

I recommend you do not use a module-level singleton to share state in this way. Use something like a [context](https://svelte.dev/docs/svelte#setcontext) and use the `context` option of `render` to populate each test with its own context that is not shared across tests

**Comment by KlashReik** [comment]
Using context instead of `<script context="module">` has fixed the errors. I've updated the repo for everyone who needs to have a look. Thanks a lot!
