### ISSUE TITLE
Writing proper tests without using the component reference

### ISSUE THREAD

**Issue by YogliB** [testing-library/svelte-testing-library#57]
I need to test certain functionalities in my component, and for that, I need to be able to listen to custom events, update props and access exported functions from the component.

Is there a way to do that without using the actual component reference?

**Comment by mihar-22** [comment]
Hey @YogliB,

In general, the idea behind the testing library is that you work with actual DOM nodes rather than instances of rendered Svelte components. This means your tests focus mostly on changes to the DOM that take place when certain props change or events fire. I'd need to see your tests to help you better but I'll leave general cases below.

**For firing custom events you can do:**

Inner.svelte

```js
<script>
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()

  function dispatchEvent () {
    dispatch('message', {
      text: 'apples'
    })
  }
</script>

<button on:click={dispatchEvent}>Click to send message</button>
```

Outer.svelte

```js
<script>
  import Inner from './Inner.svelte'

  function handleMessage (event) {
    alert(event.detail.text)
  }
</script>

<Inner on:message={handleMessage}/>
```

Test

```js
import { render, fireEvent } from '@testing-library/svelte'

import Outer from './Outer'

test('my custom event fired', async () => {
  window.alert = jest.fn()

  const { getByText } = render(Outer)

  const button = getByText('Click to send message')

  await fireEvent.click(button)

  expect(alert).toBeCalledWith('apples')
})

```

**Updating props:**

```js
import { render, fireEvent } from '@testing-library/svelte'

import Comp from '..'

test('my props change', () => {
  const { rerender } = render(Comp, { props: { myProp: 0 } })
  
  // Expect something here...

  // Change myProp
 rerender(Comp, { props: { myProp: 1 } })
 
  // Expect something here...
})
```

**Exported functions:**

This is a special case since it might not rely on any changes in the DOM. I was just thinking about this the other day, either we (1) simply compile (using svelte) and test these cases without using the `render` function from the testing library, or (2) maybe we keep the component as a return result and I'll clarify in the docs what cases it's best suited for.

**Comment by YogliB** [comment]
You can see all of the tests [here](https://github.com/YogliB/svelte-fullcalendar/blob/master/tests/FullCalendar.spec.js).

The "problematic" ones are the third and fourth.

**Comment by mihar-22** [comment]
So to me your third test is a simple unit test that falls under that special case I mentioned above. There'd be no other way to validate that function. Which makes me think we should continue to return the component as part of the testing library, as a convenience for those situations.

I haven't looked into anything deeply, but I guess you could rewrite your fourth test by passing in the callback as a prop, and causing the `datesRender` event to trigger by interacting with the DOM. I guess it depends on the level of testing you are trying to achieve. How you have it now is more a unit test, the way I suggested would be closer to an integration test.

Based on this I'll rewrite the docs soon and not make using component sound so bad. We can suggest some use cases for it.

**Comment by mihar-22** [comment]
If that's all @YogliB  we can close the issue :)

**Comment by YogliB** [comment]
Thanks!

**Comment by kentcdodds** [comment]
If I may add my thoughts here. The third test (`should expose an API`) doesn't actually test your component at all. The only part of your code it "tests" is verify that `getApi` returns the calendar because the rest of the test simply interacts with the calendar which is basically testing the third party code directly (which is not recommended). I wouldn't personally even bother keeping that test around.

The fourth test (`Should accept a callback`) is interacting with your component in a way that is entirely different from the way an end user would interact with your component. How does the `datesRender` event get dispatched in your app? There must be *some* user-interaction which makes that happen. What interaction is that? Make your test do that.

I'm not suggesting that there's not nuance and trade-offs here, there definitely are. And it's possible to test implementation details with React as well, but it's a lot harder and that difficulty is intentional. I would personally discourage exposing the component like it is done today because it makes it too easy and testing implementation details is the natural way to test. We need to make it harder so people think critically before they try it.

**Comment by YogliB** [comment]
@kentcdodds 

So using "official" terms, you'd suggest integrate-testing it rather than unit-testing it (like in @mihar-22  example)?

**Comment by kentcdodds** [comment]
Yup 👍
