### ISSUE TITLE
svelte-template files, dependencies and scripts

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#8]
Are the `svelte-template` files (`public` directory, ...) and dependencies (`rollup-plugin-livereload`, `sirv-cli`, ...) still useful and used for development, or do you think they could be removed?

Can the dependencies `@babel/runtime` and `core-js` be removed?

Old `svelte-template` scripts should maybe be removed as well if it's of no use anymore?

The documentation also mentions that `svelte` is a `peerDepedency` of this module, but it's currently only listed as a `devDependency`. Maybe that should be added as well?

**Comment by benmonro** [comment]
yes, it's useful for running the examples locally, the associated dependencies are all devDeps as well.

 @babel/runtime - that's required by jest in order to work properly, if you can find a way around that, i'll definitely put a 🎉  emoji on that PR. :)

core-js, removes some errors in travis.  again, if you can remove that, 🎉 

I added the Peer dep.
